# Generated by Django 4.2.5 on 2023-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('win', models.IntegerField()),
            ],
        ),
    ]
